
spring:
  application:
    globalconstants:
      agenda:
        lesson:
          status:
            booked: booked
            canceled: canceled
    errors:
      invalid_token:
        code: AU-101
        message: Invalid token.
      lesson_already_booked:
        code: AG-101
        message: The lesson has already been booked, it is not possible to modify it.
      canceled_lesson:
        code: AG-102
        message: Another type of error message...
      general:
        code: GE-101
        message: Unknow error

