
spring:
  application:
    globalconstants:
      agenda:
        lesson:
          status:
            booked: booked
            canceled: canceled
    errors:
      code: E-101
      message: The lesson has been already booked, it is not possible modified it.




