
spring:
  application:
    globalconstants:
      agenda:
        lesson:
          status:
            booked: booked
            canceled: canceled
    errors:
      lesson_already_booked:
        code: E-101
        message: The lesson has already been booked, it is not possible to modify it.
      canceled_lesson:
        code: E-102
        message: Another type of error message...




