
spring:
  application:
    globalconstants:
      agenda:
        lesson:
          status:
            booked: booked
            canceled: canceled
    errors:
      E_101:
        message: The lesson has already been booked, it is not possible to modify it.
      E_102:
        message: Another type of error message...




